PUB-1437 Send Headers to third party
hmcts/pip-publication-services pull request #107
Opened 2022-07-14 13:13 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1437

### Change description ###

Send header information given in ticket to third party

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-07-14 16:32 UTC, ChrisS1512 requested changes

2022-07-14 16:32 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Sensitivity.java
> +    PUBLIC, CLASSIFIED, INTERNAL, PRIVATE
INTERNAL can be removed

2022-07-14 16:32 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
> +            return new Consumer<HttpHeaders>() {
Rather than returning a new consumer here, could we return httpHeaders -> {} instead?

2022-07-15 09:48 UTC, junaidiqbalmoj commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +                                          .setHeader("name", "name")
no, removed.

2022-07-15 09:49 UTC, junaidiqbalmoj commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
>                                                "Content-Type",
I spent time on this. I am **unable to get the Custom header** in the response. Below are the header we are always getting:

[Content-Type:"text/plain;charset=UTF-8", Content-Length:"48", X-Content-Type-Options:"nosniff", X-XSS-Protection:"1; mode=block", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY"]

2022-07-15 09:50 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Sensitivity.java
> +    PUBLIC, CLASSIFIED, INTERNAL, PRIVATE
removed

2022-07-15 09:50 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
> +            return new Consumer<HttpHeaders>() {
updated.

2022-07-15 11:02 UTC, ChrisS1512 requested changes

2022-07-15 11:02 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
> +                artefact.getDisplayFrom() != null ? artefact.getDisplayFrom().toString() :
I don't believe display from can be null looking through DM - so this check for null isn't required :)

2022-07-15 11:02 UTC, ChrisS1512 commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
>                                                "Content-Type",
No worries! Happy to leave this

2022-07-15 11:23 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
> +                artefact.getDisplayFrom() != null ? artefact.getDisplayFrom().toString() :
code has been removed.

2022-07-15 12:09 UTC, furnivall approved these changes
Looks good. Nice tests!

2022-07-18 14:27 UTC, merged