Pub 1310 draft PR to check against civil list
hmcts/pip-publication-services pull request #110
Opened 2022-07-18 20:28 UTC by furnivall

Basically just for Chris (or Junaid) to verify that the civil cause list code makes sense.

2022-07-24 10:36 UTC, joshblackmoor requested changes
Just one variable name change. Have seen a demo from you and looks good :)

2022-07-24 10:36 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +        boolean sorryPmd = sittingNode.size() > 1;
Can this boolean name be changed from sorryPmd?

2022-07-25 09:23 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +            outputString.append(processCivilDailySittings(thisCourtRoom, sessionChannel));
You are using the fluent style to append to outputString in the previous line. It is not on this and the next line. May be we should keep it consistent and using the fluent '.append()' here too.

2022-07-25 10:05 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +            if (counter < length) {
Think we can just use "if (johNode.hasNext())" as the condition here and do not need "length" and "counter"?

2022-07-26 09:14 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +        boolean sorryPmd = sittingNode.size() > 1;
done, but begrudgingly

2022-07-26 09:16 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +        if (sorryPmd) {
boolean name change here

2022-07-26 09:18 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +        boolean sorryPmd = sittingNode.size() > 1;
May be better to use a more descriptive name

2022-07-26 09:18 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +            if (counter < length) {
man this was a really silly mistake. I even used johNode.hasNext() as the loop condition. Silly danny.

2022-07-26 09:18 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +            outputString.append(processCivilDailySittings(thisCourtRoom, sessionChannel));
fixed this now.

2022-07-26 09:22 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +        if (sorryPmd) {
sorted

2022-07-26 09:41 UTC, joshblackmoor approved these changes
Looks good 👍

2022-07-26 09:43 UTC, KianKwa approved these changes

2022-07-26 14:59 UTC, ChrisS1512 requested changes

2022-07-26 14:59 UTC, ChrisS1512 commented on config/owasp/suppressions.xml
> +  <suppress>
Wondering if this is still needed as the master build ran yesterday. Could you try removing it and see if it still passes?

2022-07-26 14:59 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ArtefactSummaryService.java
> +        } else {
Don't need the extra else here :)

2022-07-27 15:05 UTC, ChrisS1512 approved these changes

2022-08-01 11:29 UTC, merged