PUB-1307 Pdf for Family Daily Cause List
hmcts/pip-publication-services pull request #117
Opened 2022-07-27 16:44 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1307

### Change description ###

Create Pdf for Family Daily Cause list and merge the case information in email placeholder.

![Image 27-07-2022 at 17 43](https://user-images.githubusercontent.com/84805836/181303230-6ed6169d-341a-4c2d-9baf-1309b3a2204c.jpg)

![Image 27-07-2022 at 16 41](https://user-images.githubusercontent.com/84805836/181303273-931f4093-f009-46d6-a753-730ef7a14e07.jpg)

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-07-28 09:39 UTC, KianKwa commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    /*private static final String VALID_SUBS_EMAIL = "{\n"
Think everyone is creating their owned subscription test so we don't need the existing test now. This can possiby be removed

2022-07-28 09:40 UTC, KianKwa commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    /*
Could be removed

2022-07-28 09:42 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryService.java
> +@SuppressWarnings("PMD.TooManyMethods")
Is this a redundant suppression? Can't see many methods in this case :)

2022-07-28 09:43 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/FamilyDailyCauseList.java
> +
The empty space could be removed

2022-07-28 09:46 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +@SuppressWarnings("PMD")
Do we want to suppress all PMD here?

2022-07-28 09:47 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/FamilyDailyCauseList.java
> +@SuppressWarnings("PMD")
Some PMD are useful checks rather that suppressing all

2022-07-28 09:50 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +                return "h:mma";
DO not need an 'else' here because it is returning when it reaches there

2022-07-28 09:50 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +        } else {
Same here. Dont need the else statement. Can just return

2022-07-28 09:52 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +        ZonedDateTime zonedDateTime = unZonedDateTime.atZone(zone);
For the first 3 lines, u can just call convertStringToUtc() method below

2022-07-28 09:57 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +            return "";
Could remove the 'else' and return the value directly

2022-07-28 09:57 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +            return duration + " " + format;
Same here. Could remove the 'else' and return the value directly

2022-07-28 10:05 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryService.java
> +@SuppressWarnings("PMD.TooManyMethods")
I think it was originally there when everything was in one class - that's my bad - this is probably a good place to remove it though - 1310 is already in test.

2022-07-28 10:10 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DataManipulationTest.java
> +        assertEquals(venueAddress.get(venueAddress.toArray().length - 1),
We could just sue venueAddress.get(venueAddress.size() - 1) to get the last element if a list here

2022-07-28 10:10 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DataManipulationTest.java
> +            .isEqualTo(true);
Better to use isTrue()

2022-07-28 10:11 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DataManipulationTest.java
> +            .isEqualTo("");
IsEmpty() is better here?

2022-07-28 10:11 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DataManipulationTest.java
> +            .isEqualTo(true);
isTrue()

2022-07-28 10:17 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/HelpersTest.java
> +package uk.gov.hmcts.reform.pip.publication.services.service.pdf.helpers;
This test class is under /service/pdf/helpers but the main class is under /service/helpers...could we choose the same folder for that please?

2022-07-28 10:19 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryServiceTest.java
> +            String body = new String(mockFile.readAllBytes());
The first 3 lines here are repeated in all test methods. Could we move that into a private method which takes in that resource path as a parameter and return the string body?

2022-07-28 10:21 UTC, ChrisS1512 requested changes

2022-07-28 10:21 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +        if (hearing.has("party")) {
Slight bug on the ordering here. If a representative appears before the applicant in the JSON, it appears in the list as "Legal Advisor: AdvisorName, Applicant", where as it should be "Applicant, Legal Advisor: AdvisorName"

2022-07-28 10:26 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +            sitting.get("channel").forEach(channel -> {
As the code in the for each is the same for both Channel and sessionChannel, you could define a consumer which then gets inserted into the for each https://www.geeksforgeeks.org/java-8-consumer-interface-in-java-with-examples/

2022-07-28 10:30 UTC, furnivall requested changes

2022-07-28 10:30 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +    private static void findAndManipulatePartyInformation(JsonNode hearing) {
we should replace this method with the logic from 1484 - it should handle the cases where Representatives come before applicants or respondents. Don't worry, it's only 4 lines or so different.

2022-07-28 10:31 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +        if (hearing.has("party")) {
This is solved in 1484 - can be implemented from that :)

2022-07-28 10:32 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +            sitting.get("channel").forEach(channel -> {
oh I love this idea!

2022-07-28 10:58 UTC, junaidiqbalmoj commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    /*private static final String VALID_SUBS_EMAIL = "{\n"
removed.

2022-07-28 10:59 UTC, junaidiqbalmoj commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    /*
removed

2022-07-28 10:59 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryService.java
> +@SuppressWarnings("PMD.TooManyMethods")
removed

2022-07-28 10:59 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/FamilyDailyCauseList.java
> +
removed

2022-07-28 10:59 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +@SuppressWarnings("PMD")
removed PMD and fix the warnings.

2022-07-28 10:59 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/FamilyDailyCauseList.java
> +@SuppressWarnings("PMD")
removed PMD and fix the warnings.

2022-07-28 10:59 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +                return "h:mma";
removed else.

2022-07-28 10:59 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +        } else {
removed else.

2022-07-28 11:00 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +        ZonedDateTime zonedDateTime = unZonedDateTime.atZone(zone);
call the method for three lines.

2022-07-28 11:00 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +            return "";
removed else.

2022-07-28 11:00 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/Helpers.java
> +            return duration + " " + format;
removed else.

2022-07-28 11:00 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DataManipulationTest.java
> +        assertEquals(venueAddress.get(venueAddress.toArray().length - 1),
as discussed, fixed.

2022-07-28 11:00 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DataManipulationTest.java
> +            .isEqualTo(true);
fixed.

2022-07-28 11:00 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DataManipulationTest.java
> +            .isEqualTo("");
fixed.

2022-07-28 11:00 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DataManipulationTest.java
> +            .isEqualTo(true);
fixed.

2022-07-28 11:00 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/HelpersTest.java
> +package uk.gov.hmcts.reform.pip.publication.services.service.pdf.helpers;
fixed.

2022-07-28 11:01 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryServiceTest.java
> +            String body = new String(mockFile.readAllBytes());
made a new method to read the file. thanks.

2022-07-28 11:32 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryServiceTest.java
> +        } catch (IOException ex) {
Apology...we could remove the catch clause here. The exception is re-throw in the method signature so doesn't need to be handled. Don't worry if you are not making anymore changes. We could just leave it.

2022-07-28 12:56 UTC, ChrisS1512 requested changes

2022-07-28 12:56 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +    public static void manipulatedDailyListData(JsonNode artefact) {
to prevent this class getting too big, I feel like this method should live in the CivilDailyCauseListConverter, as it's specific to the civil cause list. This class could then be generic / more of a helper class that multiple lists could use

2022-07-28 13:38 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +    private static void findAndManipulatePartyInformation(JsonNode hearing) {
I fixed the bug.

2022-07-28 13:38 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryServiceTest.java
> +        } catch (IOException ex) {
removed.

2022-07-28 13:39 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/helpers/DataManipulation.java
> +    public static void manipulatedDailyListData(JsonNode artefact) {
this method is not only for CivilDailyCauseList. This function is being used for for Daily, family and mix lists as well.

2022-07-28 14:48 UTC, KianKwa approved these changes

2022-07-28 15:40 UTC, ChrisS1512 approved these changes

2022-08-03 11:04 UTC, ChrisS1512 commented
Merged in as part of Mixed list

2022-08-03 11:04 UTC, closed without merging