PUB-1360 Pdf for Civil and Family Daily Cause List
hmcts/pip-publication-services pull request #118
Opened 2022-07-28 16:29 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1360

### Change description ###

Create Pdf for Civil and Family Daily Cause list and merge the case information in email placeholder.

![Image 28-07-2022 at 17 26](https://user-images.githubusercontent.com/84805836/181589901-a1d0b951-0fa3-4190-bcb6-438cbea7c661.jpg)

![Image 28-07-2022 at 17 26 (1)](https://user-images.githubusercontent.com/84805836/181589923-f2e42c96-898c-4498-9672-97cd0ce182de.jpg)

![Image 28-07-2022 at 17 26](https://user-images.githubusercontent.com/84805836/181589952-0015a9f3-dc5a-4e89-ac0e-7b5543359715.jpg)

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-07-29 11:59 UTC, KianKwa commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    void testValidPayloadForSubsCivilAndFamilyCauseListListEmailReturnsOk() throws Exception {
Typo in the test name....it says "ListList" :)

2022-07-29 12:07 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/converters/CivilAndFamilyDailyCauseListConverter.java
> +@SuppressWarnings("PMD.AvoidInstantiatingObjectsInLoops")
There is nothing in loop in this method so do not need this PMD suppression. Probably just copying error from Danny's one

2022-07-29 12:10 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/CivilAndFamilyDailyCauseList.java
> +public class CivilAndFamilyDailyCauseList {
This class looks identical to the Family one. Is the Civil one the same too? May be just need a single class called 'DailyCauseList' to cover them all?

2022-07-29 15:24 UTC, junaidiqbalmoj commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    void testValidPayloadForSubsCivilAndFamilyCauseListListEmailReturnsOk() throws Exception {
fixed :)

2022-07-29 15:25 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/converters/CivilAndFamilyDailyCauseListConverter.java
> +@SuppressWarnings("PMD.AvoidInstantiatingObjectsInLoops")
removed.

2022-07-29 15:25 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/CivilAndFamilyDailyCauseList.java
> +public class CivilAndFamilyDailyCauseList {
yes, you are right. I created on class DailyCauseList and use in both Family and Mix list.

2022-07-29 15:33 UTC, KianKwa approved these changes

2022-07-29 15:43 UTC, KianKwa approved these changes

2022-07-29 16:04 UTC, ChrisS1512 requested changes

2022-07-29 16:04 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/DailyCauseList.java
> +    public String processDailyCauseList(JsonNode node) {
Could we get away without the appendToStringBuilders in the method below and use .append? (Especially for the \n's)

2022-07-29 16:04 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/Helpers.java
> +@SuppressWarnings("PMD.TooManyMethods")
I've split this out into a couple of different helper classes which managed to get rid of the annoation above in the PR for 1361 - could we do the same here?

2022-07-29 16:14 UTC, furnivall approved these changes
Looks good man nice work :D

2022-08-01 09:34 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/DailyCauseList.java
> +    public String processDailyCauseList(JsonNode node) {
I was using .append, but PMD was complaining. Now, I have refactor this function completely.

2022-08-01 09:35 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/Helpers.java
> +@SuppressWarnings("PMD.TooManyMethods")
Move all helper functions into relevant helper classes and update the test classes as well.

2022-08-01 15:10 UTC, ChrisS1512 approved these changes

2022-08-03 11:00 UTC, merged