PUB-1306 Add Civil daily cause list HTML conversion for PDF generation
hmcts/pip-publication-services pull request #119
Opened 2022-07-28 16:30 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1306

### Change description ###

Add Civil daily cause list HTML conversion for PDF generation. This is based on Junaid's PR for PUB-1307

Generated PDF

![image](https://user-images.githubusercontent.com/80688761/181590187-ccbfdc68-638a-42e0-aeab-f76da8dba325.png)

![image](https://user-images.githubusercontent.com/80688761/181590240-4b2a66b9-506d-43ce-92c1-54f5faf1a676.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-07-29 11:40 UTC, KianKwa commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    void testValidPayloadForSubsFamilyCauseListListEmailReturnsOk() throws Exception {
The test name has duplicated words "ListList" :)

2022-07-29 16:23 UTC, ChrisS1512 requested changes

2022-07-29 16:23 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/templatemodels/SjpPressCase.java
> +public class SjpPressCase {
I can't see this used in this PR - could be removed?

2022-07-29 16:23 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/FamilyDailyCauseList.java
> +                            hearing.get("case").forEach(hearingCase -> {
I'm wondering if we need the appendToStringBuilder here and could use append instead?

2022-07-29 18:39 UTC, furnivall reviewed
Great stuff - it looks good when built, and  the build passes - you can really implement whatever you like of my suggestions, although the blue text probably should go imo. Let me know and I'll approve when you need :)

2022-07-29 18:39 UTC, furnivall commented on src/main/resources/templates/civilDailyCauseList.html
> +      color: darkblue;
Change the colour here to #0b0c0c - it's an artefact of my original template - sorry.

2022-07-29 18:39 UTC, furnivall commented on src/main/resources/templates/civilDailyCauseList.html
> +    pre p {
This whole element can be chucked - another artifact of my earlier exploration.

2022-07-29 18:39 UTC, furnivall commented on src/main/resources/templates/familyCauseList.html
> +        content: "This is PDF/UA page " counter(page) " of " counter(pages) ".";
To match Junaid's and mine, you could add "Court and Tribunal Hearings Service to this, so the code is like:

```content: "Court and Tribunal Hearings Service - PDF/UA page " counter(page) " of " counter(pages) ".";```

Totally up to you though.

2022-07-29 18:39 UTC, furnivall commented on src/main/resources/templates/familyCauseList.html
> +  </div>
To make this trailing last page look a bit less weird (and to match mine and Junaid's) you can add the following code:

```<hr/>
<p style="font-family: 'GDS Transport'; font-size: 24px;">Note this document contains Special Category Data as defined by Data Protection Act 2018, formally known as Sensitive Personal Data, and should be handled appropriately.</p>
<p style="font-family: 'GDS Transport'; font-size: 24px;">This document contains information intended to assist the accurate reporting of court proceedings. It is vital you ensure that you safeguard the Special Category Data included and abide by reporting restrictions (for example on victims and children). HMCTS will stop sending the data if there is concern about how it will be used.</p>
<hr/>
<p style="text-align: center;">Thank you for reading this document thoroughly.</p>```

2022-07-29 18:39 UTC, furnivall commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/converters/CivilDailyCauseListConverterTest.java
> +class CivilDailyCauseListConverterTest {
I just love your tests dude, they're so meticulous.

2022-08-01 08:11 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/templatemodels/SjpPressCase.java
> +public class SjpPressCase {
Ohh thank you. Think Danny's has renamed the class and something has gone wrong in the merge. Will remove

2022-08-01 08:19 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/FamilyDailyCauseList.java
> +                            hearing.get("case").forEach(hearingCase -> {
Agreed this looks a bit weird. Think Junaid did that to fix some PMD issues but it could be fixed differently. He has renamed this class in his PR so I don't think I will change it here. May be raise that in his PR instead?

2022-08-01 12:14 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/FamilyDailyCauseList.java
> +                            hearing.get("case").forEach(hearingCase -> {
Junaid mentioned he has fixed it in his branch

2022-08-01 15:29 UTC, KianKwa commented on src/main/resources/templates/civilDailyCauseList.html
> +      color: darkblue;
Updated 'color' to #0b0c0c

2022-08-01 15:29 UTC, KianKwa commented on src/main/resources/templates/civilDailyCauseList.html
> +    pre p {
Have been removed

2022-08-01 15:29 UTC, KianKwa commented on src/main/resources/templates/familyCauseList.html
> +        content: "This is PDF/UA page " counter(page) " of " counter(pages) ".";
I have updated it to be consistent with others :)

2022-08-01 15:30 UTC, KianKwa commented on src/main/resources/templates/familyCauseList.html
> +  </div>
The comment is for Family list, I have made the same change in Civil list

2022-08-01 15:31 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/converters/CivilDailyCauseListConverterTest.java
> +class CivilDailyCauseListConverterTest {
Thank you Danny. You always have such kind words :)

2022-08-01 15:34 UTC, furnivall approved these changes

2022-08-02 11:07 UTC, ChrisS1512 approved these changes

2022-08-03 14:37 UTC, merged