PUB-1359 - SSCS daily list pdf
hmcts/pip-publication-services pull request #134
Opened 2022-08-01 21:08 UTC by furnivall

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-1359

### Change description ###
PDF and List Summary Text methods for SSCS Daily List

PDF: 
![image](https://user-images.githubusercontent.com/18507008/182246676-4e418918-cf76-40d5-b820-b381e0521583.png)
![image](https://user-images.githubusercontent.com/18507008/182246692-4831d8c0-f2f6-4a4f-b66a-35f4c8c9998b.png)

List Summary:
![image](https://user-images.githubusercontent.com/18507008/182246932-6522baa7-fe38-4609-adcc-8c9c63af0dab.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-08-02 08:17 UTC, KianKwa commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    @ValueSource(strings = {"SSCS Daily List", "SJP Public List", "SJP Press List"})
Love the parameterizedTest...much neater but can we not passing in the json strings directly to ValueSource so we don't need the Map? 
@ValueSource(strings = {VALID_SCSS_DAILY_LIST_SUBS_EMAIL, VALID_SJP_PUBLIC_SUBS_EMAIL, VALID_SJP_PRESS_SUBS_EMAIL})

2022-08-02 08:32 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/converters/SscsDailyListConverter.java
> +                path = "templates/languages/sscs-english.json";
It is probably alright here because we only using English only. I wonder once we have the other languages and other list types, might be better to create subfolders for English, Welsh and Bilingual.

2022-08-02 08:48 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/Helpers.java
> +            List<String> sessionChannel = new ObjectMapper().readValue(
Might be better to add a constant for ObjectMapper creation at the top of the class so it does not need to be kept instantiated inside the loop. Might be able to get rid of that PMD suppression

2022-08-02 08:50 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/converters/SscsDailyListConverter.java
> +                path = "templates/languages/sscs-english.json";
Yeah, I think this is a decent idea. The cleanup ticket will be responsible for putting this in.

2022-08-02 08:51 UTC, furnivall commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    @ValueSource(strings = {"SSCS Daily List", "SJP Public List", "SJP Press List"})
Yeah, had to do it this way to make sure the error could let us know where the problem was :)

2022-08-02 11:28 UTC, ChrisS1512 requested changes

2022-08-02 11:28 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/converters/SjpPublicListConverter.java
> +
Extra line can be removed :)

2022-08-02 11:28 UTC, ChrisS1512 commented on src/main/resources/templates/sscsDailyList.html
> +  <p class="govuk-body govuk-font-14" th:text="${i18n.dataSource + metadata.provenance}"/>
I think we'll want the data warning in the footer (similar to the ones that were added to the SJP lists)

2022-08-02 12:25 UTC, furnivall commented on src/main/resources/templates/sscsDailyList.html
> +  <p class="govuk-body govuk-font-14" th:text="${i18n.dataSource + metadata.provenance}"/>
Isn't this what's on line 224 and 225? It's pulling from the language file.

2022-08-02 12:32 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/Helpers.java
> +            List<String> sessionChannel = new ObjectMapper().readValue(
Have now done this :)

2022-08-02 12:34 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/converters/SjpPublicListConverter.java
> +
sortedd

2022-08-02 12:50 UTC, KianKwa approved these changes

2022-08-02 13:33 UTC, ChrisS1512 commented on src/main/resources/templates/sscsDailyList.html
> +  <p class="govuk-body govuk-font-14" th:text="${i18n.dataSource + metadata.provenance}"/>
Oops yep it is

2022-08-02 13:33 UTC, ChrisS1512 approved these changes

2022-08-04 10:16 UTC, ChrisS1512 requested changes

2022-08-04 10:16 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PdfCreationService.java
> +            "location", location.getName(),
I have a feeling a few of the lists use locationName here rather than location. Worth a quick check through the html's

2022-08-04 10:16 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/pdf/helpers/DateHelper.java
> +    public static String formatTimestampToBst(String timestamp) {
This method is the same as formatTimestampToBstForSjp - could combine. Feel free to ignore to do in cleanup

2022-08-04 12:11 UTC, ChrisS1512 approved these changes

2022-08-04 12:12 UTC, merged