PUB-1316 Media user verification email
hmcts/pip-publication-services pull request #136
Opened 2022-08-04 11:31 UTC by joshblackmoor

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1316

### Change description ###

Added new endpoint to send the media verification email. 

![Screenshot 2022-08-04 at 12 30 25](https://user-images.githubusercontent.com/23316525/182836708-fae944e6-1b56-4a57-9774-b8016a628470.png)

Note: A placeholder link has been included for now until the link up tickets are played.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-08-05 15:11 UTC, ChrisS1512 requested changes

2022-08-05 15:11 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
> +        personalisation.put(VERIFICATION_PAGE_LINK, "https://placeholder-link.com");
Rather than the placeholder, could we set up the environment var pass through from application yaml for this - just so it's all ready when we get the link

2022-08-05 15:37 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
> +        personalisation.put(VERIFICATION_PAGE_LINK, "https://placeholder-link.com");
Done :) Will come back in and replace the https://www.gov.uk when we have the correct link. Will also put them in SDS flux at the same time.

2022-08-05 16:14 UTC, KianKwa approved these changes

2022-08-05 16:42 UTC, furnivall approved these changes

2022-08-05 16:42 UTC, furnivall approved these changes
What a great piece of work. You are definitely "working above"

2022-08-23 09:08 UTC, ChrisS1512 approved these changes

2022-08-23 09:09 UTC, merged