PUB-1543 - Lists to Excel
hmcts/pip-publication-services pull request #162
Opened 2022-09-12 16:09 UTC by joshblackmoor

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1543

### Change description ###

- Developed solution to generating excel spreadsheets from JSON payloads (only SJP Public currently)
- Refactored existing pdf package to filegeneration which contains code relating to pdf and excel generation
- Refactored pdf creation service  to file creation service which includes pdf, excel and csv generation (removing CSV generation service)

Note: Template to be updated before merging
Note: 3600 SJP cases is roughly a 67kb PDF

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-09-13 11:21 UTC, ChrisS1512 requested changes

2022-09-13 11:21 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/converters/SjpPublicListConverter.java
> +                artefact.get("courtLists").get(0)
On a similar vein to the issues with sessions, hearings etc, rather than pulling back only the first one, can we make this dynamic to handle whatever structure is used?

2022-09-13 12:47 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/converters/SjpPublicListConverter.java
> +                artefact.get("courtLists").get(0)
As per discussion this will be covered under a new ticket where the PDF & Frontend will be updated

2022-09-13 16:54 UTC, KianKwa approved these changes

2022-09-14 16:01 UTC, ChrisS1512 approved these changes

2022-09-21 12:14 UTC, merged