Generate Excel spreadsheet for all MI data
hmcts/pip-publication-services pull request #193
Opened 2022-10-20 11:00 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1551

### Change description ###

Generate a single Excel spreadsheet with 4 sheets containing all MI data

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-20 15:40 UTC, ChrisS1512 requested changes

2022-10-20 15:40 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @PostMapping("/mi-data")
It's probably just me, but I tend to avoid '-' in paths.

Something like '/mi/report' or '/mi/data' feels better. What do you think?

2022-10-20 15:40 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/GlobalExceptionHandler.java
> +        log.error(writeLog(String.format("ExcelCreationException was thrown with the init cause: %s", ex.getCause())));
Log messages are the wrong way round on these (CSV / Excel needs swapping)

2022-10-20 15:40 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementService.java
> +            return webClient.get().uri(String.format("%s/account/mi-data", url))
I think you'll need to set it to use the client registration ID for account management below, as the default is Data management

2022-10-20 15:40 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionManagementService.java
> +            return webClient.get().uri(String.format("%s/subscription/mi-data-all", url))
Similar to above (will need the subscription management client registration set)

2022-10-20 15:40 UTC, ChrisS1512 commented on src/main/resources/application.yaml
> +  subscription-management: ${SUBSCRIPTION_MANAGEMENT_URL:https://pip-subscription-management.staging.platform.hmcts.net}
You'll also need an SDS Flux PR for these for the other env's (I'd be tempted to keep it separate to the cron one)

2022-10-21 07:47 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @PostMapping("/mi-data")
I don't like hyphen either. Was just trying to make it the same as the other mi endpoints. Actually I don't need to . This endpoint is more about generating the report. The other other ones are for pulling the data. Has renamed to /mi/report :)

2022-10-21 07:47 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/GlobalExceptionHandler.java
> +        log.error(writeLog(String.format("ExcelCreationException was thrown with the init cause: %s", ex.getCause())));
Oops. Updated :)

2022-10-21 07:48 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementService.java
> +            return webClient.get().uri(String.format("%s/account/mi-data", url))
Added client registration ID

2022-10-21 07:48 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionManagementService.java
> +            return webClient.get().uri(String.format("%s/subscription/mi-data-all", url))
Added client registration ID

2022-10-21 08:04 UTC, KianKwa commented on src/main/resources/application.yaml
> +  subscription-management: ${SUBSCRIPTION_MANAGEMENT_URL:https://pip-subscription-management.staging.platform.hmcts.net}
Added a PR with the env variables added https://github.com/hmcts/sds-flux-config/pull/2306

2022-10-21 15:58 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @PostMapping("/mi-data")
Looks good, thanks :)

2022-10-24 08:27 UTC, ChrisS1512 requested changes

2022-10-24 08:27 UTC, ChrisS1512 commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementServiceTest.java
> +        mockPublicationServicesEndpoint = new MockWebServer();
Only minor but I think this should be mockAccountManagementEndpoint

2022-10-25 08:04 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementServiceTest.java
> +        mockPublicationServicesEndpoint = new MockWebServer();
I have renamed this one and other test files with the same issue.

2022-10-25 08:17 UTC, ChrisS1512 approved these changes

2022-10-25 10:24 UTC, joshblackmoor approved these changes

2022-11-02 07:03 UTC, joshblackmoor approved these changes
Approval for functional tests

2022-11-02 07:49 UTC, ChrisS1512 approved these changes

2022-11-03 13:43 UTC, merged