PUB-1586 Send PDF/Excel from storage
hmcts/pip-publication-services pull request #195
Opened 2022-10-21 11:20 UTC by joshblackmoor

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1586
https://tools.hmcts.net/jira/browse/PUB-1588

### Change description ###

- Removed all artefact summary, PDF and Excel related code
- Set up link to channel management
- Updated services to retrieve data from channel management to send in the email

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-25 10:34 UTC, ChrisS1512 requested changes

2022-10-25 10:34 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
> +
Can we add some Java docs to the methods below

2022-10-25 10:34 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
> +@SuppressWarnings({"PMD.PreserveStackTrace", "PMD.ImmutableField"})
Is the ImmutableField supression needed to be supressed here?

2022-10-25 10:34 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
> +            byte[] artefactPdf = publicationFiles.get("PDF");
Could we make this an ENUM rather than a string?

2022-10-25 13:30 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
> +            byte[] artefactPdf = publicationFiles.get("PDF");
Done, updated channel management with same.

2022-10-25 13:30 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
> +@SuppressWarnings({"PMD.PreserveStackTrace", "PMD.ImmutableField"})
Done

2022-10-25 13:30 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
> +
Done

2022-10-25 15:01 UTC, KianKwa approved these changes

2022-10-31 17:23 UTC, ChrisS1512 approved these changes

2022-11-04 14:59 UTC, merged