PUB-1362 ET Daily List PDF and artefact summary generation
hmcts/pip-publication-services pull request #196
Opened 2022-10-25 14:40 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1362

### Change description ###

ET Daily List PDF and artefact summary generation

<img width="760" alt="image" src="https://user-images.githubusercontent.com/80688761/197804152-0bbaa4f7-f2d2-4d90-aa9c-4c594d61a8c2.png">

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/80688761/197804252-1716388d-3963-49fa-b259-55dff0b628ab.png">

![image](https://user-images.githubusercontent.com/80688761/197803893-d82fac79-effe-4372-94d8-98c60104d0a6.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-10-25 16:42 UTC, ChrisS1512 requested changes

2022-10-25 16:42 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/EtDailyList.java
> +                                    .append("\t•Start Time: ")
I think you can use GeneralHelper.appendToStringBuilder for the below (it also handles nulls)

2022-10-26 08:26 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/EtDailyList.java
> +                                    .append("\t•Start Time: ")
Updated

2022-10-26 09:40 UTC, ChrisS1512 requested changes

2022-10-26 09:40 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/listmanipulation/EtDailyListManipulation.java
> +    private static String createIndividualDetails(JsonNode party) {
Could we use the createIndividualDetails from Data Manipulation here? It does look a bit different but potentially does the same

2022-10-26 10:00 UTC, ChrisS1512 approved these changes

2022-10-26 12:45 UTC, joshblackmoor approved these changes
LGTM 👍

2022-10-28 10:57 UTC, merged