PUB-1363 Fortnightly Press List Pdf
hmcts/pip-publication-services pull request #197
Opened 2022-10-26 12:41 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1363

### Change description ###

Pdf Template for Fortnightly Press List

![1](https://user-images.githubusercontent.com/84805836/198028393-cf16ea11-a86e-4306-a0e2-bccdf2ca4e8b.jpg)

![2](https://user-images.githubusercontent.com/84805836/198028429-5f2cc9cb-07c5-4216-ab84-2ca68e9caa6f.jpg)

![3](https://user-images.githubusercontent.com/84805836/198028456-698d3579-ea23-45a7-978c-da4e5fec16e0.jpg)

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2022-10-26 16:02 UTC, KianKwa commented on src/main/resources/templates/etFortnightlyPressList.html
> +      <p th:text="${artefact.get('venue').get('venueName').asText() +  ', ' + artefact.get('venue').get('venueContact').get('venueEmail').asText() + ', ' + artefact.get('venue').get('venueContact').g
Think this should be on the same line as openJustice4 as shown in the mock

2022-10-26 16:21 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +package uk.gov.hmcts.reform.pip.publication.services.service.filegeneration.helpers;
There is a folder called 'listManipulation' under the helpers directory. This folder is getting large so might want to consider moving the lists specific class into that folder

2022-10-26 16:23 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +                            ((ObjectNode)hearing).put("claimant",
Can move the party stuff from line 96 to 104 to a private method to make this main method here more readable.

2022-10-26 16:33 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +        String rep = (language == Language.ENGLISH) ?  "Rep" : "Cynrychiolydd";
The language folder under the resource folder is for storing the language variances. This is passed into the main method in this class preprocessArtefactForEtFortnightlyListThymeLeafConverter(). You can just pass the map into this method and use the resource file. Try avoiding hardcoding the Welsh text in the code.

2022-10-26 16:46 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +                (sittingNode).put(SITTING_DATE, uniqueSittingDate.get(finalI));
Is this finalI not just i? Do you really need the variable finalI?

2022-10-26 16:49 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +    public static final String COURT_ROOM = "courtRoom";
If these constants not going to be used outside the class, make them private

2022-10-26 16:56 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +                    if (!uniqueDate.contains(sittingDate)) {
You could just use Set rather than List. This will handle the deduplication for you and no need to check whether the array contains it. If you want to maintain the oder of insertion, just use LinkedHashSet

2022-10-26 16:59 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +            for (int i = 0; i <= uniqueSittingDate.size() - 1; i++) {
You can just use i < uniqueSittingDate.size(). There are 2 redundant operations here. One for checking equal or another one to subtract 1 from the size.

2022-10-26 17:00 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationServiceTest.java
>          Location location = new Location();
The same location is set 3 times in the test class. Could just add a BeforeAll and set it once in the top of the class

2022-10-26 17:07 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/PartyRoleHelper.java
> +                    forename = forename + (forename.length() > 0 ? "." : "");
The mock file in the ticket don't have an extra dot after the initial. Do we not want to keep them the same?

2022-10-26 17:13 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +            return claimant + ", "
In the mock, the representative follows the claimant/respondent by a new line and not a comma. We might want to keep it the same. If you do, you will find that thymeleaf text does not work if you pass in a '\n' in the string to the html converter. If might be best to separate out the claimant/respondent from the representative here, and use thymeleaf utext to join them together using <br/>

2022-10-27 08:26 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/PartyRoleHelper.java
> +                    forename = forename + (forename.length() > 0 ? "." : "");
I'm gonna be honest - I added the dot in the frontend as it looked way better than without. Junaid likely just copied my implementation.

2022-10-27 08:42 UTC, junaidiqbalmoj commented on src/main/resources/templates/etFortnightlyPressList.html
> +      <p th:text="${artefact.get('venue').get('venueName').asText() +  ', ' + artefact.get('venue').get('venueContact').get('venueEmail').asText() + ', ' + artefact.get('venue').get('venueContact').g
done.

2022-10-27 08:42 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +package uk.gov.hmcts.reform.pip.publication.services.service.filegeneration.helpers;
done.

2022-10-27 08:46 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +                (sittingNode).put(SITTING_DATE, uniqueSittingDate.get(finalI));
I cannot use **I**. IntelliJ is giving me error, just follow the recommendation from IntelliJ

2022-10-27 08:46 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +    public static final String COURT_ROOM = "courtRoom";
done.

2022-10-27 08:46 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +                    if (!uniqueDate.contains(sittingDate)) {
done. Set is new for me :)

2022-10-27 08:47 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +            for (int i = 0; i <= uniqueSittingDate.size() - 1; i++) {
done.

2022-10-27 08:47 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationServiceTest.java
>          Location location = new Location();
done.

2022-10-27 08:47 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/PartyRoleHelper.java
> +                    forename = forename + (forename.length() > 0 ? "." : "");
done.

2022-10-27 08:47 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelper.java
> +            return claimant + ", "
done.

2022-10-27 09:05 UTC, ChrisS1512 requested changes

2022-10-27 09:38 UTC, KianKwa commented on src/main/resources/templates/languages/cy/etFortnightlyPressList.json
> +{
The number of lines for the Welsh version is less than the English one. Think something is missing here. Might be "Data Source"? Please check

2022-10-27 09:42 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelperTest.java
> +package uk.gov.hmcts.reform.pip.publication.services.service.filegeneration.helpers;
The main file has been moved into a sub-folder. Need to keep the main and test file in some folder structure

2022-10-27 09:49 UTC, KianKwa commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelperTest.java
> +    private static Map<String, Object> language;
What you need is just "rep". You could just do "_language = Map.of("rep", "Rep: ")_" here, and can remove the beforeAll code below to read the entire resource file. Can also remove the json language file for test, and make the method handleLanguage back to be a private method

2022-10-27 11:29 UTC, junaidiqbalmoj commented on src/main/resources/templates/etFortnightlyPressList.html
> +                <h3 th:text="${sitting.get('sittingDate').asText()}" />
fixed.

2022-10-27 11:30 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/EtFortnightlyPressListHelperTest.java
> +    private static Map<String, Object> language;
agreed :) thanks. it's fixed.

2022-10-27 14:28 UTC, ChrisS1512 approved these changes

2022-10-31 11:57 UTC, merged