PUB-1747 Send PDF to Courtel for json publications
hmcts/pip-publication-services pull request #233
Opened 2022-12-22 15:50 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1747

### Change description ###

Send PDF to Courtel for json publications

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-12-23 10:46 UTC, ChrisS1512 requested changes

2022-12-23 10:46 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementService.java
> +    public String handleThirdParty(ThirdPartySubscriptionArtefact body) {
Could we add delete or similar to this method name, just to highlight it's for the removal

2022-12-23 12:08 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementService.java
> +    public String handleThirdParty(ThirdPartySubscriptionArtefact body) {
Have updated the method name to notifyThirdPartyForArtefactDeletion :)

2022-12-23 15:34 UTC, joshblackmoor approved these changes

2023-01-09 16:58 UTC, ChrisS1512 approved these changes

2023-01-11 10:43 UTC, merged