PUB-1769 MI report enhancement
hmcts/pip-publication-services pull request #253
Opened 2023-01-26 11:40 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1769

### Change description ###

MI report enhancement

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-27 17:41 UTC, ChrisS1512 submitted a review, later dismissed

2023-01-27 17:41 UTC, ChrisS1512 requested changes
Just some conflicts :) Then happy to approve

2023-01-30 11:11 UTC, junaidiqbalmoj approved these changes

2023-01-30 12:23 UTC, joshblackmoor approved these changes

2023-02-03 11:04 UTC, ChrisS1512 approved these changes

2023-02-03 11:04 UTC, merged