PUB-1663 Clear Subscription
hmcts/pip-publication-services pull request #265
Opened 2023-02-07 10:16 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1663

### Change description ###

Add email template to send email to subscribers when their subscription is being deleted by System Admin as part of Delete court journey.

**Does this PR introduce a breaking change?** (check one with "x")
[ ] Yes
[x] No

2023-02-10 17:11 UTC, ChrisS1512 requested changes

2023-02-10 17:11 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @ApiResponse(responseCode = OK_RESPONSE, description = "Unidentified blob email "
OK response message needs updating

2023-02-10 17:11 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    public ResponseEntity<String> sendDeleteLocationSubscriptionEmail(
I would update this to be generic, maybe just deleteLocation, as we also include the artefact deletion too in this template (I think)

2023-02-10 17:11 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    public ResponseEntity<String> sendDeleteLocationSubscriptionEmail(
(Also similarly other classes will renaming too to be generic)

2023-02-13 10:19 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @ApiResponse(responseCode = OK_RESPONSE, description = "Unidentified blob email "
thanks, updated.

2023-02-13 17:32 UTC, ChrisS1512 approved these changes

2023-02-22 16:14 UTC, KianKwa approved these changes

2023-02-23 15:57 UTC, merged