PUB-1916 Update README file
hmcts/pip-publication-services pull request #291
Opened 2023-03-24 17:32 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1916

### Change description ###

Update README file

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-28 09:19 UTC, ChrisS1512 requested changes

2023-03-28 09:19 UTC, ChrisS1512 commented on README.md
> +  - Notification emails to all system admin users when a location and its associated publications or subscriptions are being deleted by a system admin.
I'm debating if this should be a generic - system admin's get emailed about certain audit actions, or whether to expand the list to include all available audit actions that have emails sent. Happy either way

2023-03-28 09:19 UTC, ChrisS1512 commented on README.md
> +- `gov-uk-notify-api-key` - Live key for sending of official CaTH emails.
There's also a team key which we should add here

2023-03-28 09:19 UTC, ChrisS1512 commented on README.md
It might be worth highlighting here the process of adding a new field to a template - in that you have to create a copy of the template first for local testing, then deploy the code change, and then update the main template.

2023-03-28 09:19 UTC, ChrisS1512 commented on README.md
> +- Docker - used to run integration tests due to our use of [TestContainers](https://www.testcontainers.org/)
Docker can be removed here

2023-03-28 13:12 UTC, KianKwa commented on README.md
> +  - Subscription related emails to media users when new publications are uploaded to CaTH, or when a user’s subscriptions are being deleted as a result of routine maintenance of locations within CaTH
Replacing 'media' with 'verified'

2023-03-28 13:13 UTC, KianKwa commented on README.md
> +- Integration tests using TestContainers for dummy database operations.
Removed

2023-03-28 13:24 UTC, KianKwa commented on README.md
> +- `gov-uk-notify-api-key` - Live key for sending of official CaTH emails.
Added team key too

2023-03-28 13:24 UTC, KianKwa commented on README.md
> +- Docker - used to run integration tests due to our use of [TestContainers](https://www.testcontainers.org/)
Removed

2023-03-28 13:29 UTC, KianKwa commented on README.md
> +| PI_TEAM_EMAIL                      | The email address for sending CaTH reporting emails (e.g. media applications, mi reports, unindentified blobs) to.
Updated

2023-03-28 13:29 UTC, KianKwa commented on README.md
> +| PI_TEAM_EMAIL                  | As above                                                                               |
Updated

2023-03-28 13:39 UTC, KianKwa commented on README.md
Added separate sentences for this.

2023-03-29 07:52 UTC, ChrisS1512 approved these changes

2023-03-29 15:35 UTC, junaidiqbalmoj approved these changes
LGTM :)

2023-03-30 10:04 UTC, merged