PUB-2300 Add security to Swagger API
hmcts/pip-publication-services pull request #416
Opened 2024-02-13 18:23 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-2300

### Change description ###

Add security to Swagger API

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-02-15 16:52 UTC, ChrisS1512 requested changes

2024-02-15 16:52 UTC, ChrisS1512 commented on config/owasp/suppressions.xml
> +  <suppress>
This can now be removed

2024-02-19 08:56 UTC, KianKwa commented on config/owasp/suppressions.xml
> +  <suppress>
Removed the suppresion

2024-02-19 10:53 UTC, ChrisS1512 approved these changes

2024-02-20 15:31 UTC, ChrisS1512 approved these changes

2024-02-20 17:23 UTC, ChrisS1512 approved these changes

2024-02-21 16:02 UTC, merged