Pub 708 notify for new aad user
hmcts/pip-publication-services pull request #52
Opened 2022-03-23 09:59 UTC by furnivall

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-708

### Change description ###
Implemented sending emails based on new azure accounts.
Will include a new user flow for password setting in the future.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-03-24 09:15 UTC, ChrisS1512 requested changes
We should add some integration tests for the new endpoint

2022-03-24 09:15 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @PostMapping("/aad-welcome-email")
I'm thinking the email for the admin sign in is going to be different than the media sign in.

Thinking this should be 'admin' welcome email, rather than aad (and similar with the naming of the responses / models)

2022-03-24 11:42 UTC, kurt-uk requested changes

2022-03-24 11:42 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @PostMapping("/aad-welcome-email")
^^ yup, this is admin, its based on new created account
something like `/created/admin`

2022-03-24 11:42 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +    private static final String AAD_SIGNIN_LINK = "https://pib2csbox.b2clogin.com/pib2csbox.onmicrosoft.com/oauth2/v2"
^^ yup, can move this to the application file, same as the other personalisation links

2022-03-24 11:42 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +    }
this isnt emailService logic, this is logic that determines which notification to send, this should be back up a level, EmailService should be concerned with constructing contents of an email, other service should manage which which kind of email to send

2022-03-24 11:42 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +        personalisation.put("sign_in_page_link", AAD_SIGNIN_LINK);
pop these keys as vars as they could easily change in future and would be easier to maintain

2022-03-24 11:42 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
> +        SendEmailResponse response = emailService.sendEmail(welcomeEmail);
can merge this line and return together

2022-03-24 20:57 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +    private static final String AAD_SIGNIN_LINK = "https://pib2csbox.b2clogin.com/pib2csbox.onmicrosoft.com/oauth2/v2"
Sorted, have done as @kurt-uk suggests :)

2022-03-24 20:58 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @PostMapping("/aad-welcome-email")
Sorted :)

2022-03-24 20:59 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
> +    NEW_AZURE_USER_WELCOME_EMAIL("77a658c5-7c69-4dcc-984e-214a3c37cea2");
Sorted :)

2022-03-24 21:02 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +        personalisation.put("sign_in_page_link", AAD_SIGNIN_LINK);
sorted :)

2022-03-24 21:30 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +    }
Have moved it into the notificationService handleWelcomeEmailRequest method now - can I just clarify that that's what you mean? Cheers

2022-03-24 21:31 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +    protected EmailToSend buildAadWelcomeEmail(AadWelcomeEmail body) {
Yeah, good shout. Could you have a quick check and just make sure I've done it how you'd imagined?

2022-03-24 21:33 UTC, furnivall commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
> +        SendEmailResponse response = emailService.sendEmail(welcomeEmail);
done :)

2022-03-25 19:22 UTC, furnivall commented
> We should add some integration tests for the new endpoint

Have added this now :)

2022-04-05 16:08 UTC, ChrisS1512 submitted a review, later dismissed

2022-04-06 10:21 UTC, kurt-uk submitted a review, later dismissed

2022-04-06 10:28 UTC, kurt-uk approved these changes

2022-04-06 13:39 UTC, alberto-hortiguela submitted a review, later dismissed

2022-04-26 11:50 UTC, ChrisS1512 approved these changes

2022-04-26 12:27 UTC, kurt-uk commented on config/owasp/suppressions.xml
> +  </suppress>
can we add this to https://tools.hmcts.net/confluence/display/PUBH/Suppressions+in+services

2022-04-26 12:48 UTC, kurt-uk requested changes

2022-04-26 12:48 UTC, kurt-uk commented on Jenkinsfile_CNP
> +      secret('gov-uk-notify-api-key', 'NOTIFY_API_KEY')
this has to be diff to the actual key we use, this key needs to be test key, and values.yaml needs to be valid key

2022-04-26 12:51 UTC, furnivall commented on config/owasp/suppressions.xml
> +  </suppress>
Already in there :)

2022-04-26 14:56 UTC, ChrisS1512 approved these changes

2022-04-26 15:02 UTC, kurt-uk approved these changes

2022-04-26 15:04 UTC, merged