PUB 1269 send media applications report
hmcts/pip-publication-services pull request #69
Opened 2022-05-26 12:19 UTC by joshblackmoor

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1269

### Change description ###

- Added new endpoint to handle sending media requests
- Added new Csv creation service
- Added new env variable for the team email which comes from the key vault
- Converted maps to be <String, Object> rather than <String, String> (this is required for sending files and does not break existing notifications)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-26 15:58 UTC, joshblackmoor commented
> Details

Done :)

2022-05-26 15:59 UTC, joshblackmoor commented
> Looks good! Needs some integration tests adding for new the endpoint too

Done :)

2022-05-30 10:13 UTC, kurt-uk requested changes

2022-05-30 10:13 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/CsvCreationService.java
> +            log.error("Error occurred %s when trying to create a csv with list %s",
logging an error where youre throwing an exception isnt needed, the exception should handle the logging of whats gone wrong, especially if its our exception

2022-05-30 12:35 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/CsvCreationService.java
> +            log.error("Error occurred %s when trying to create a csv with list %s",
Ah yes. Removed that line 👍

2022-06-07 08:44 UTC, kurt-uk approved these changes

2022-06-07 16:43 UTC, ChrisS1512 approved these changes

2022-06-15 14:38 UTC, merged