added third party subscription api
hmcts/pip-publication-services pull request #75
Opened 2022-06-07 14:40 UTC by kurt-uk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-949

### Change description ###
Added api for sending third party subscriptions, takes in third party body containing artefact id and the destination url, added S2S call to data mangement and added int tests. 
added placeholders for cert provided by courtel, currently using testing values (InsecureTrustManager)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-10 10:39 UTC, joshblackmoor approved these changes

2022-06-13 17:19 UTC, ChrisS1512 requested changes

2022-06-13 17:19 UTC, ChrisS1512 commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    //@Test
This needs uncommenting out

2022-06-13 17:19 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
> +                log.info(thirdPartyService.handleCourtelCall(body.getApiDestination(),
Can we make the methods names generic rather than specific to courtel

2022-06-14 12:53 UTC, ChrisS1512 commented on src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
> +    //@Test
Resolving as covered in another PR

2022-06-20 11:00 UTC, closed without merging