Pub-981 error handle third party
hmcts/pip-publication-services pull request #76
Opened 2022-06-13 09:15 UTC by kurt-uk

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-981

### Change description ###
Added retry to third party service. will retry 3 times, logging after each, before throwing exception returning the repsonse code from third party.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-13 17:21 UTC, ChrisS1512 requested changes

2022-06-13 17:21 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
> +            .retryWhen(Retry.backoff(3, Duration.ofSeconds(2))
Could we move the times + seconds into config just in case it needs updating in the future?

2022-06-14 12:54 UTC, ChrisS1512 approved these changes

2022-06-14 13:05 UTC, joshblackmoor approved these changes

2022-06-20 10:58 UTC, merged