PUB-1254 Media User Emails
hmcts/pip-publication-services pull request #78
Opened 2022-06-14 08:33 UTC by junaidiqbalmoj

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1254

### Change description ###

Send email to media users on account creation.

**Does this PR introduce a breaking change?** (check one with "x")
[] Yes
[x] No

2022-06-16 12:24 UTC, kurt-uk requested changes
Youve also missed off the integration tests

2022-06-16 12:24 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @PostMapping("/created/duplicate/media")
this wouldnt be `created` this is more of an error isnt it? its saying there was an error and nothing was done because the account is a duplicate

2022-06-16 12:24 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +            "Created duplicate media account email successfully sent with referenceId %s",
similar to the above, this message is confusing as there isnt a created duplicate media account,
something more appropriate to the situation would be best as the response

2022-06-16 12:24 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/CreateMediaSetupEmail.java
> +public class CreateMediaSetupEmail {
```suggestion
public class DuplicatedMediaEmail {
```

2022-06-23 08:14 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    @PostMapping("/created/duplicate/media")
change it to /notify/duplicate/media

2022-06-23 08:14 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +            "Created duplicate media account email successfully sent with referenceId %s",
change wording.

2022-06-23 08:14 UTC, junaidiqbalmoj commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/request/CreateMediaSetupEmail.java
> +public class CreateMediaSetupEmail {
renamed.

2022-06-23 12:37 UTC, kurt-uk requested changes
youre still missing your integration tests

2022-06-27 13:10 UTC, ChrisS1512 requested changes
Conflicts need sorting on this now that base branch switched to master

2022-06-28 14:39 UTC, joshblackmoor approved these changes

2022-06-28 15:37 UTC, ChrisS1512 approved these changes

2022-06-29 09:09 UTC, kurt-uk requested changes

2022-06-29 09:09 UTC, kurt-uk commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
> +        validRequestBodyTrue = new WelcomeEmail(VALID_EMAIL, TRUE_BOOL, "FULL_NAME");
youve wrapped this in quotes instead of using the value of FULL_NAME, is that right? did you not mean to use the static var?

2022-06-29 09:35 UTC, junaidiqbalmoj commented on src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
> +        validRequestBodyTrue = new WelcomeEmail(VALID_EMAIL, TRUE_BOOL, "FULL_NAME");
Good catch, fixed.

2022-07-08 13:39 UTC, merged