PUB-711 - Added welcome email api
hmcts/pip-publication-services pull request #8
Opened 2021-09-27 13:00 UTC by kurt-uk

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-711

### Change description ###

### API
endpoint created for `/notify/welcome-email that take in a body of email and isExisting and returns a string with referenceId of the welcome email sent

### services and models
EmailToSend model created that contains the fields necessary for Gov notify to send an email.
Notification service created to extract the logic from the controller, it handles the request that comes in and then passes parsed json data to the email service which then does the processing for the email, such as building it and sending.

### Exceptions
3 new exceptions created;
BadPayloadException - thrown when the body isnt in proper json format or when parsing the json fails (eg incorrect bool values in the bool variable) - returns a 400 bad request with the exception message
NotifyException - catches the NotificationException and throws a PIP exception where notify fails to send an email, returns a 400 bad request and the exception message, bad request is thrown as the main cause of NotificationException is wrong template or email or missing personalisation which is is then passed in the error back up in the response

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-09-27 13:03 UTC, marcogagliardi commented on Jenkinsfile_CNP
>  ]
not sure but it looks like the indent is wrong

2021-09-27 14:07 UTC, marcogagliardi commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +        }
if we are using the global exception handler can we move the throw exception to the business layer? in this way we avoid to have try/catch in the controller.

2021-09-27 14:08 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +        }
the global exception handler is being used here too, this exception is thrown if invalid json is passed into the api

2021-09-27 14:08 UTC, kurt-uk commented on Jenkinsfile_CNP
>  ]
ive ran it though the linter to check and it stayed the same, which part do you think isnt indented correctly?

2021-09-27 15:06 UTC, marcogagliardi commented on Jenkinsfile_CNP
>  ]
line 12

2021-09-27 15:07 UTC, marcogagliardi commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +        }
ok

2021-09-28 08:43 UTC, ChrisS1512 requested changes

2021-09-28 08:43 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +            throw (NotifyException)new NotifyException(e.getMessage()).initCause(e);
Rather than the explicit cast to NotifyException, can we remove the initCause (or pass the raw exception into NotifyException) which should remove the need for the cast.

2021-09-28 08:43 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +    protected Map<String, String> buildWelcomePersonalisation() {
Rather than this being run on each email creation, I'm wondering if this would fit better in the constructor of this class as it will generate the same personalisation each time.

2021-09-28 08:43 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
> +            throw (BadPayloadException) new BadPayloadException(e.getMessage()).initCause(e);
Similar comment here regarding casting (is it possible to remove the explicit cast)

2021-09-28 09:18 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/client/EmailClient.java
> +public class EmailClient extends NotificationClient {
👍🏼

2021-09-28 09:20 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    public ResponseEntity sendWelcomeEmail(@RequestBody String body) {
👍🏼

2021-09-28 09:20 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    public ResponseEntity sendWelcomeEmail(@RequestBody String body) {
👍🏼

2021-09-28 09:27 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
> +public enum Templates {
👍🏼

2021-09-28 12:59 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    public ResponseEntity sendWelcomeEmail(@RequestBody String body) {
Spring cant deserialize json coming in from a request so if i try use JSONObject as the param type it just passes around an empty json (`{}`) you would have to use some kind of object mapper to do so but that would exist in the code and would therefore make that removal of string to new JsonObject redundant. if you know of another way ill give it a go but i did some research and found that Spring cant deserialise without some input

2021-09-28 13:53 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +            throw (NotifyException)new NotifyException(e.getMessage()).initCause(e);
changed to the standard e.getMessage()

2021-09-28 13:55 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
> +    protected Map<String, String> buildWelcomePersonalisation() {
I was trying to make sure that `EmailService.java` is generic as future emails will have their own personalisation, this is specific to welcome emails, i could put it in the constructor now, however just means little refactor later on so i thought defensively and put it in own method. With this, would you still rather in constructor for now?

2021-09-28 16:09 UTC, ChrisS1512 commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    public ResponseEntity sendWelcomeEmail(@RequestBody String body) {
Makes sense. Thinking about it further, does our object always have the same set of keys? 

If so we could create a model that represents that object and pass that through. That would save on the conversion and also remove the need to check if the keys exist in the Notification Service (we'll get some build in type safety for free too)

2021-09-29 09:53 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
> +    public ResponseEntity sendWelcomeEmail(@RequestBody String body) {
good shout, updated

2021-09-29 10:41 UTC, ChrisS1512 approved these changes

2021-10-14 08:27 UTC, timja commented on build.gradle
> +  implementation 'junit:junit:4.13.1'
do you need this? generally we exclude junit 4 and use junit 5 everywhere

2021-10-14 08:28 UTC, timja commented on build.gradle
> +  annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
what do you need this for that's not included already by say the spring boot plugin?

2021-10-14 08:28 UTC, timja commented on config/pmd/ruleset.xml
> +    <exclude name="JUnitTestsShouldIncludeAssert"/>
why do you need this?

2021-10-14 08:29 UTC, timja commented on config/pmd/ruleset.xml
> +    <exclude name="PreserveStackTrace"/>
again why? this is a very important rule for logging.

If you think you have one place where it doesn't make sense then you should exclude it there and not everywhere.

(but maybe there's something wrong with this rule)

2021-10-14 08:39 UTC, kurt-uk commented on src/test/resources/application.yaml
> +    key: pipkeyfortesting-d43606f7-ccc7-486c-8847-f5bdf21c938d-7033ceaf-4fdf-4c72-84a8-d916762ddbeb
yes it does nothing, you cant send any emails with this what so ever,

2021-10-14 08:40 UTC, kurt-uk commented on src/test/resources/application.yaml
> +    key: pipkeyfortesting-d43606f7-ccc7-486c-8847-f5bdf21c938d-7033ceaf-4fdf-4c72-84a8-d916762ddbeb
its a test key that mocks sending emails

2021-10-14 08:44 UTC, timja commented on src/test/resources/application.yaml
> +    key: pipkeyfortesting-d43606f7-ccc7-486c-8847-f5bdf21c938d-7033ceaf-4fdf-4c72-84a8-d916762ddbeb
probably better to use a less real looking one

2021-10-14 16:04 UTC, merged